name: Tests

on: [push]

jobs:
  equality_test:
    name: Equality test
    runs-on: windows-latest
    
    steps:
    - name: Checkout to workspace
      uses: actions/checkout@master

    - name: Set bot's name and email
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "action@github.com"

    - name: Emulating merge commit to origin/master
      run: |
        git checkout origin/master
        git merge --no-ff %GITHUB_SHA%

    - name: Run MySQL server
      run: mysqld --initialize --console

    - name: First echo
      run: echo UPDATE mysql.user SET authentication_string=PASSWORD('root') WHERE User='root'; > reset.sql
        
    - name: Second echo
      run: |
        echo FLUSH PRIVILEGES; >> reset.sql
        
    - name: Try mysqld --init-file
      run: start /b mysqld --init-file="D:\a\mmp-practicum-sql-fall-2019\mmp-practicum-sql-fall-2019\reset.sql"

    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Initialize database
      run: echo "quit" | mysql -uroot -proot --connect-expired-password

    - name: Cloning data
      run: |
        git clone https://github.com/CrafterKolyan/mmp-practicum-sql-fall-2019-db-dump.git data
        cd data
        cat trjudge_sql_dump_2019.zip.part? > trjudge_sql_dump_2019.zip
        unzip trjudge_sql_dump_2019.zip
        cd ..

    - name: Installing MySQLdb and multiset
      run: |
        sudo apt install libmysqlclient-dev
        pip3 install setuptools
        pip3 install mysqlclient multiset

    - name: Run equality test
      run: util/test_equality.py
